import { z } from "zod";

export const productoSchema = z.object({
  tipo: z.enum(["SIMPLE", "VARIABLE", "AGRUPADO", "EXTERNO"]).default("SIMPLE"),
  sku: z.string().min(1, "SKU requerido").max(50),
  nombre: z.string().min(2, "Nombre requerido").max(255),
  slug: z.string().max(255).optional(),
  publicado: z.boolean().default(false),
  visibilidad: z.string().default("visible"),
  destacado: z.boolean().default(false),
  descCorta: z.string().max(500).optional().nullable(),
  descripcion: z.string().optional().nullable(),
  seoTitulo: z.string().max(70).optional().nullable(),
  seoDescripcion: z.string().max(200).optional().nullable(),
  seoKeywords: z.array(z.string()).optional(),
  seoTexto: z.string().optional().nullable(),
  precioNormal: z.number().positive("El precio debe ser positivo").optional().nullable(),
  precioOferta: z.number().positive().optional().nullable(),
  estadoImpuesto: z.string().optional().nullable(),
  claseImpuesto: z.string().optional().nullable(),
  enStock: z.boolean().default(true),
  stock: z.number().int().min(0).default(0),
  stockMinimo: z.number().int().min(0).default(15),
  permiteBackorders: z.enum(["no", "notify", "yes"]).default("no"),
  pesoKg: z.number().positive().optional().nullable(),
  largoCm: z.number().positive().optional().nullable(),
  anchoCm: z.number().positive().optional().nullable(),
  altoCm: z.number().positive().optional().nullable(),
  categorias: z.array(z.string()).default([]),
  etiquetas: z.array(z.string()).default([]),
  claseEnvio: z.string().optional().nullable(),
  notaCompra: z.string().optional().nullable(),
  permiteResenas: z.boolean().default(true),
  acfSkuInterno: z.string().optional().nullable(),
  acfMarcaFabricante: z.string().optional().nullable(),
  acfUnidadVenta: z.string().optional().nullable(),
  acfFabricacionMedida: z.boolean().default(false),
  acfInstalacion: z.boolean().default(false),
  acfGarantiaAnos: z.number().int().min(0).optional().nullable(),
  acfAplicaciones: z.array(z.string()).default([]),
  acfColores: z.array(z.string()).default([]),
  acfNormas: z.array(z.string()).default([]),
  acfFichaTecnicaPdf: z.string().url("URL inválida").optional().nullable(),
  acfCertificaciones: z.array(z.string()).default([]),
  acfExtra: z.record(z.unknown()).optional().default({}),
  intEstado: z.enum(["BORRADOR", "REVISION", "LISTO", "PUBLICADO", "ARCHIVADO"]).default("BORRADOR"),
  intResponsable: z.string().optional().nullable(),
  intObservaciones: z.string().optional().nullable(),
  intListoExportar: z.boolean().default(false),
});

export const filtrosProductosSchema = z.object({
  busqueda: z.string().optional(),
  categoria: z.string().optional(),
  estado: z.enum(["BORRADOR", "REVISION", "LISTO", "PUBLICADO", "ARCHIVADO"]).optional(),
  publicado: z.coerce.boolean().optional(),
  stockCritico: z.coerce.boolean().optional(),
  page: z.coerce.number().int().min(1).default(1),
  limit: z.coerce.number().int().min(1).max(100).default(25),
  orderBy: z.enum(["updatedAt", "nombre", "sku", "precioNormal", "stock"]).default("updatedAt"),
  order: z.enum(["asc", "desc"]).default("desc"),
});

export type ProductoInput = z.infer<typeof productoSchema>;
export type FiltrosProductosInput = z.infer<typeof filtrosProductosSchema>;
